### ISSUE TITLE
namespace::autoclean update issues

### ISSUE THREAD

**Issue by Scimon** [bscan/PerlNavigator#102]
I updated Perl Navigator on VSCode this morning to version 0.7.7 and started getting compilation errors in code that was working fine before the update and only in VSCode. These errors seem to be because the DateTime module is expecting a version of namespace::autoclean.

Again I can use DateTime (and namespace::autoclean with versioning) outside VSCode it's just breaking internally. I noticed the changelog for yesterday included a mention of namespace::autoclean and I wonder if the fix for that may have broken it's usage in code with versioning?

**Comment by Scimon** [comment]
I've rolled back to 0.7.4 for now. (The bug does seem to have come in with 0.7.5 which is where the update to namespace::autoclean is mentioned).

**Comment by pders01** [comment]
Noticed exactly the same behaviour.

**Comment by bscan** [comment]
Hi @Scimon and @pders01, sorry about that and thank you for reporting the issue. namespace::clean and namespace:autoclean had been giving me trouble regarding interactions the symbol table because they both delete elements from the table before I can inspect it.

I just pushed out another version of the Navigator (0.7.8) that tries to work around these issues by faking a version of clean/autoclean, which now works for me on loading `DateTime`. Let me know if you see any other issues. Thanks!

**Comment by Scimon** [comment]
I'll give it a shot now.

**Comment by Scimon** [comment]
That's look good now. Thanks for the speedy response!

**Comment by pders01** [comment]
Seconded! Also great new features. Thanks for your work @bscan.

**Comment by bscan** [comment]
Great, thank you both!
