### ISSUE TITLE
Publish 0.8.0 to open-vsx registry

### ISSUE THREAD

**Issue by maros** [bscan/PerlNavigator#111]
Latest version available at https://open-vsx.org/extension/bscan/perlnavigator is 0.5.1

Thank you very much for your effort

**Comment by bscan** [comment]
Good call. I just published version 0.8.0 to open-vsx, which has quite a few new features since 0.5.1. 
The biggest ones are probably the pod documentation on hover, subroutine signatures, improved better navigation, and the recently improved syntax highlighting. 

Eventually, I'd like to improve the deploy process to include tests, and automatic deployment to open-vsx, the vscode marketplace, and NPM. I'll publish 0.8.0 to npm this week as well, although the primary new feature since 0.7.13 is the syntax highlighting, which doesn't really impact npm users.

Thanks!
