### ISSUE TITLE
Feature request: local language server

### ISSUE THREAD

**Issue by Reissner** [bscan/PerlNavigator#137]
Maybe this is already implemented and I did not find.

My point is, that I dont want to move my code into the internet, 
not even for being checked by a language server. 
The only way to use a language server (which I love) 
is to use a loal one. 

Is there a way to install?

**Comment by rabbiveesh** [comment]
All editors run the language server locally - why do you think anything
else is occuring?

**Comment by bscan** [comment]
Hi @Reissner, yes you are likely already running it entirely locally, especially based on the issue in #136 where it showed Perl warnings. When running normally, Perl Navigator does not require a web connection and does not make any web requests for telemetry, functionality, or required assets. 

The one exception is when running in web-mode (press `.` in a browser when viewing any Github repo). The Perl Navigator works in this web based version of vscode, but is limited in functionality. Because we can't run Perl in a browser, it does not have syntax checking, perlcritic, or perltidy. However, as you can see in the image, you can still get sticky-scroll, outline view, improved syntax highlighting, and some go-to definition and hover. This method of using the Perl Navigator is uncommon, although I'd love to know if anyone is using it this way. Standard installations via vscode and npm are entirely local. 

![image](https://github.com/user-attachments/assets/6e37071d-fe29-4313-80a8-3fff86aaa460)
