### ISSUE TITLE
Display a files path relative to scope of file in error message

### ISSUE THREAD

**Issue by miversen33** [bscan/PerlNavigator#14]
When perlnavigator receives an error from (I assume) perlcritic, the entire absolute path to the file in question is displayed in the error. This is a bit unwieldy and at times can actually be useless (if the path is long enough to be obscured from the window).
![Neovim](https://user-images.githubusercontent.com/2640668/169873422-aa28b23e-298e-4d22-9e9c-79cdc0961a71.png)
![vscode](https://user-images.githubusercontent.com/2640668/169873632-fc444bfc-0b38-4b90-bf72-5ed452b23eec.png)

Other LSPs dont display the name of the current file in the error (likely as its assumed)
Example of PerlPLS
![Neovim](https://user-images.githubusercontent.com/2640668/169873810-be9bc1d3-16c5-47b8-9fac-137314d2dd8a.png)

Consider removing the current file's name from displayed error messages?

**Comment by bscan** [comment]
Thanks for the suggestion, I agree this cleans up the errors. I'm now removing errors and warnings whenever the error originates from the current file. This is slightly tricky and different from PLS due to the error localization. That is, when syntax checking `Foo.pl`, if an error or a warning originates from `Bar.pm`, I'll place the error on the line that says `use Bar;`. In that case, I'll keep the filename displayed. Example below:

![image](https://user-images.githubusercontent.com/10503608/212497088-2b3e9592-58eb-4f28-a476-6e7d40055959.png)

I'll push these changes to the marketplace this weekend. Thanks!
