### ISSUE TITLE
Go to definition on a class name

### ISSUE THREAD

**Issue by oalders** [bscan/PerlNavigator#144]
I'm not really clear on the internals here, but at the command line I use https://metacpan.org/dist/Open-This/view/script/ot to open arbitrary modules and even subs in those modules. Is it possible for PerlNavigator to hook into something like this ad-hoc or does everything need to be pre-parsed? For instance, if I had

```perl
use LWP::UserAgent ();
```

it would be great to open something like `~/.plenv/versions/5.40.0/lib/perl5/site_perl/5.40.0/LWP/UserAgent.pm` when I choose my "go to definition" shortcut, which is what `ot LWP::UserAgent` does for me a the command line.

**Comment by bscan** [comment]
Hi @oalders, I'm not sure I follow what you mean. When I go-to definition on `LWP::UserAgent`, it should currently jump to the top of the file, which is the found automatically from the version of perl I picked in my settings. This is found in a few different ways. When the relevant file is compiled, the inquisitor looks in `%INC` and prints all the modules loaded, which can help for dynamically located modules. It's also known when the Navigator starts up and runs `modHunter.pl`, which lists all importable modules. This also works for most subs in the module. If the wrong version is opening, perhaps you could try adding a path to the `includePaths`?

![image](https://github.com/user-attachments/assets/a89c9bcb-8dd0-442d-b685-91c9b3595eb1)

And go to definition on ->get

![GotoGet](https://github.com/user-attachments/assets/c1f2296e-0ecd-40a9-8615-509543c7ff15)

**Comment by oalders** [comment]
Thanks, @bscan. Maybe it's something in my `neovim` setup. This works for me with other LSPs, though. I'll dig around and close this if it's not relevant.

**Comment by rabbiveesh** [comment]
Ah, there's a little funny behavior here
When i do "Go to definition" on a line like this:
`use LWP::UserAgent`, if my cursor is on the `LWP`, it takes me to the package `LWP`, and only takes me to `LWP::UserAgent` if my cursor is on the `UserAgent` part

**Comment by bscan** [comment]
Hi @rabbiveesh, yes this behavior is intentional, although odd in some cases. This allows you to navigate directly to the subroutine, the containing module, or a higher level. For example, given `Foo::Bar::Baz` lets you go-to-definition and hover on `Foo`, `Foo::Bar`, and `Foo::Bar::Baz`. This is especially important in the case that `Baz` is a subroutine instead of a module. This logic is all located in: https://github.com/bscan/PerlNavigator/blob/de1344a97c883698d5630b01d8299a17a9d95148/server/src/utils.ts#L44

However, I do recognize that it's a little odd for keyboard cursor centric editors (e.g. emacs and neovim) where you may go the front of the `Foo::Bar::Baz` and expect it to find something reasonable.  

Example of the current behaviour. Note that `HTTP` doesn't find anything at all, and it's not really a parent module.

![PerlSymbols](https://github.com/user-attachments/assets/dd51f41a-c59e-4454-ba69-2c5a510ebfec)

This is also how it works in Microsoft's Python Language Server (Pylance). Although I recognize that Python is slightly different since the submodules are always part of the same distribution as the parents. In Perl however, `Foo::Bar::Baz` may or may not be distributed with `Foo::Bar`. 

![PythonSymbols](https://github.com/user-attachments/assets/fb13a7ae-0167-4914-9ddf-5540462e5426)

**Comment by oalders** [comment]
@bscan works for me with latest nightly. 🎉

**Comment by bscan** [comment]
Awesome, thanks @oalders. I'm glad it's working.
