### ISSUE TITLE
Perl::Critic not working "out of the box"

### ISSUE THREAD

**Issue by blues1875** [bscan/PerlNavigator#3]
First off, congratulations on a great extension. I'm running Strawberry perl 5.32.1 and VSCode 1.64.2 on Windows 10. I installed perlNavigator and disabled Perl Toolbox and perl-outline. Navigation, syntax checking, autocomplete and outline work as expected, but Perl::Critic doesn't flag any complaints. When I disable perlNavigator and re-enable Perl Toolbox, Perl::Critic flags as expected. Can you suggest what to check? Where do I find the LSP log?

**Comment by bscan** [comment]
Thanks for the feedback, I'm glad it's mostly working. The image below shows where the LSP log is available and it will show the critic command and output. One thing to check is the Perl path if you have multiple versions of Perl installed. Otherwise, take a look at the logs and let me know if anything jumps out. I will test with Strawberry Perl as well. One difference between Perl Toolbox and Perl Navigator is that Toolbox uses the binary (perlcritic), while Navigator uses the library ("use Perl::Critic"). This is because the library offers features that allow sending the data over stdin so the Critic can be checked without requiring saving the file like is required in the Toolbox. The binary does technically accept stdin, but doesn't allow setting the filename, which causes the Perl Toolbox to be wrong on policies that uses the filename (e.g. RequireFilenameMatchesPackage). 

If your Perl version includes the binary, but not PPI and Perl::Critic, you'll need to install those separately from CPAN. Eventually, I'd like to bundle them in the extension as well. 

![image](https://user-images.githubusercontent.com/10503608/155436968-1309565e-1666-469e-9e67-0dbbd1f995f7.png)

**Comment by blues1875** [comment]
Thanks for your quick response. The log doesn't show much of interest:

```
Now starting perlcritic with: c:\Users\Glenn\.vscode\extensions\bscan.perlnavigator-0.2.5\server\src\perl\criticWrapper.pl --file d:\pc_test.pl
Compilation Time: 0.593 seconds
[Trace - 20:20:42] Received notification 'textDocument/publishDiagnostics'.
Critic outputAnalyzing d:\pc_test.pl
Perl Critic violations:

Perl Critic Time: 2.187 seconds
[Trace - 20:20:42] Received notification 'textDocument/publishDiagnostics'.
Critic outputAnalyzing d:\pc_test.pl
Perl Critic violations:

Perl Critic Time: 2.082 seconds
[Trace - 20:20:43] Received notification 'textDocument/publishDiagnostics'.
```
I do have PPI and Perl::Critic installed and only have one perl version on the system. It's interesting to hear that perlNavigator doesn't use the perlcritic binary. I have seen spurious RequireFilenameMatchesPackage warnings in the past; that may explain them! I'll do some experimentation with the Perl::Critic module directly later to see if I discover anything.
I installed the extension on a different machine with basically the same setup, though with v 1.63.2 of VS Code. There, results are quite bizarre. For this code:
```
use experimental qw(signatures);

sub BUILD ($self, $args) {
    $self->opt_spec(\@OPT_SPEC);
    $self->argv($ARGV);
    unless ('string') { say("here"); }
}
```
it flags a problem with ProhibitSubroutinePrototypes (even with the 'use experimental' line), but doesn't mention the missing 'return' or anything about the 'unless' line. With Perl Toolbox enabled, perl critic screams blue murder on that line!

I don't have a lot of spare time at the moment, but I'll upgrade to VS Code 1.64 on that machine to see if it makes any difference. I'll also look on another machine. They all have basically the same version of perl and the same modules, but I'll try to narrow it down.

**Comment by blues1875** [comment]
Sorry, i accidentally closed this...

**Comment by bscan** [comment]
Thanks for the response and continued time on this.  I suspect the issue is with the different defaults. If you don't specify a critic profile, I'm simply using the Perl Critic defaults, which are very different from the Perl Toolbox defaults. Both sets of defaults appear to have issues:
1. Perl Toolbox has the severities entirely flipped. Critic severities are 1-5 with 5 being the most severe issue. However, the toolbox marks least severe issues as errors and the most severe issues as only informational. Perl Toolbox by default also includes all of the severity levels in the diagnostics which seems a bit strong given how the severity 1 and 2 issues are normally unimportant. 
2. Perl::Critic (and the Navigator) by default only look at the most severe (level 5) issues which happens to include ProhibitSubroutinePrototypes. That policy has an issue that flags signatures as prototypes. See https://github.com/Perl-Critic/Perl-Critic/issues/591 
This is especially problematic as signatures will no longer be experimental as of the next release of Perl. The other policy you mentioned with the final return is Subroutines::RequireFinalReturn and is a severity 4 policy, which is not shown by default. 

Try creating a critic profile file while the following settings, which I think would be reasonable and still fairly gentle (you can also mess with the severity level).
```
severity=4
[-Subroutines::ProhibitSubroutinePrototypes]
```
and then specify this profile using the `"perlnavigator.perlcriticProfile":` setting. If you go lower than severity=4, the lower severity issues will be very subtle and marked only as "hints" underneath the code. You can change these settings with `perlnavigator.severity3` for example. 

I should also update the Navigator to have better settings for people who aren't using a profile.

**Comment by bscan** [comment]
I just added a default critic profile: https://github.com/bscan/PerlNavigator/blob/main/server/src/perl/defaultCriticProfile
Still fairly lax as I don't want to annoy anyone into turning the extension off, but does set the severity to 4 instead of 5. It's also somewhat opinionated, but pretty reasonable for modern defaults.

I also added support for perltidy (both range formatting and document formatting), which uses the built-in tidy defaults if you don't have a profile set.

Supporting the Debug Adaptor Protocol would be great too, but is a longer term project. 

Thanks again for the feedback and suggestions, definitely feel free to comment more on this ticket or open up a new one.
