### ISSUE TITLE
Perlcritic failed with unknown error

### ISSUE THREAD

**Issue by oalders** [bscan/PerlNavigator#44]
I've just been messing around trying to get `perlimports` to work, but I'm struggling to get the extension up and running. My `perl` is managed via `plenv`. Here's the output I'm getting for `perlcritic` as well as the compilation check:

https://gist.github.com/oalders/fae520a36ea6cd197a31dbab226bb8f4

`settings.json`:

```json
    "perlnavigator.includePaths": [
        "/Users/olaf/.plenv/versions/5.36.0/lib/perl5/site_perl/5.36.0/",
        "/Users/olaf/.plenv/versions/5.36.0/lib/perl5/5.36.0/",
    ],
    "perlnavigator.perlPath": "/Users/olaf/.plenv/versions/5.36.0/bin/perl",
    "perlnavigator.trace.server": "verbose",
    "perlnavigator.perlcriticProfile": "/Users/olaf/.perlcriticrc",
    "perlnavigator.perltidyProfile": "/Users/olaf/.perltidyrc",
    "perlnavigator.severity1": "error",
    "perlnavigator.severity2": "error",
    "perlnavigator.severity3": "error",
    "perlnavigator.severity4": "error",
    "perlnavigator.severity5": "error",
```

I'm not seeing any kind of output even for compilation errors. If I run this command in my terminal (inside and outside of VSCode) it works:

```bash
/Users/olaf/.plenv/versions/5.36.0/bin/perl -c -Mwarnings -M-warnings=redefine -I \
/Users/olaf/.plenv/versions/5.36.0/lib/perl5/site_perl/5.36.0/ -I \
/Users/olaf/.plenv/versions/5.36.0/lib/perl5/5.36.0/ -I \
/Users/olaf/.vscode/extensions/bscan.perlnavigator-0.3.0/server/src/perl -MInquisitor \
/Users/olaf/Documents/perl-scratch/foo.pl
```

Notable, it displays the compilation error in the terminal which I was expecting to see in VSCode.

```bash
Can't locate Carpzzzzz.pm in @INC (you may need to install the Carpzzzzz module) (@INC contains: /Users/olaf/.plenv/versions/5.36.0/lib/perl5/site_perl/5.36.0//darwin-2level /Users/olaf/.plenv/versions/5.36.0/lib/perl5/site_perl/5.36.0/ /Users/olaf/.plenv/versions/5.36.0/lib/perl5/5.36.0//darwin-2level /Users/olaf/.plenv/versions/5.36.0/lib/perl5/5.36.0/ /Users/olaf/.vscode/extensions/bscan.perlnavigator-0.3.0/server/src/perl /Users/olaf/.plenv/versions/5.36.0/lib/perl5/site_perl/5.36.0/darwin-2level /Users/olaf/.plenv/versions/5.36.0/lib/perl5/site_perl/5.36.0 /Users/olaf/.plenv/versions/5.36.0/lib/perl5/5.36.0/darwin-2level /Users/olaf/.plenv/versions/5.36.0/lib/perl5/5.36.0) at /Users/olaf/Documents/perl-scratch/foo.pl line 5.
BEGIN failed--compilation aborted at /Users/olaf/Documents/perl-scratch/foo.pl line 5.
```

Any tips would be appreciated!

**Comment by bscan** [comment]
Thanks for giving it a try. This is an odd one, as the Navigator is usually pretty stable. 

Looking through the log, the error ENOENT is that node execFile can't find your version of Perl. Ideally, I should have a nice pop-up when it can't find manually specified versions of perl. I just added https://github.com/bscan/PerlNavigator/issues/46 to track this.

This line is odd: `path: ' /Users/olaf/.plenv/versions/5.36.0/bin/perl',`. It looks like there's a leading space in settings.perlPath. I see that leading space is not in your settings, but is it possible that you had a trailing space, removed it, and the language server never picked up your change? You could try:
1) Restart the Navigator by closing vscode and re-opening
2) Remove perlPath entirely from the settings to see if it picks up the default "perl" on Mac (not ideal of course since you want 5.36)
3) Otherwise, I'll try to debug it on a mac with plenv. Most of my testing is linux and windows, so perhaps something is different on Mac OS. In the past, I've come across small differences such as minor differences in how it handle pipes for example. If something is adding those spaces, perhaps I could trim leading/trailing spaces from settings. 

Thanks!
