### ISSUE TITLE
Outline does not work in some cases

### ISSUE THREAD

**Issue by hbasrc** [bscan/PerlNavigator#51]
such as using, 
`use Win32::MultiMedia::Mci;`

https://metacpan.org/release/THAMUS/Win32-MultiMedia-0.01

![2022-11-28_011855](https://user-images.githubusercontent.com/38921971/204150981-7391fe4a-8b93-4dac-99fd-21ce31fe14b8.png)

**Comment by bscan** [comment]
Thanks for the issue! The Navigator works by running `perl -c` and then inspecting the symbol table in the same process. At the end of this process, it was also parsing the current file to get symbols for the outline. However, this means that if anything crashed anywhere along the way, the outline would not get populated. 

With the version 0.7.0 release, the parsing of the current file has been rewritten in Typescript instead of running on the Perl side. This should make it much more reliable and responsive. Thanks!

**Comment by rabbiveesh** [comment]
has the 0.7.0 release hit npm?

**Comment by bscan** [comment]
@rabbiveesh, I just pushed the new release to npm. I was a bit hesitant that it might cause issues since I added dependencies on a WebAssembly package that can sometimes require a C compiler, but it seems to be working fine for me. 

There shouldn't be any new features in 0.7.0 / 0.7.1, except this reliability issue, and some enhancements to the vscode-web-browser-based version that nobody uses 😆. However, it was still a decent sized refactor in prep for some future features, so let me know if you have any issues. Thanks!
