### ISSUE TITLE
Object recognition, Autocomplete, and subroutine navigation not working

### ISSUE THREAD

**Issue by stevenwittkopf** [bscan/PerlNavigator#54]
Hi bscan! Thanks for your hard work! We are looking for a perl language server to run on our remote servers at my work. We use carton to manage our perl imports and the settings we use are like so:

```
perlnavigator.perlPath: "<output of `carton exec -- which perl` here>",
perlnavigator.includePaths: [
    "$workspaceFolder/t/lib"
    // "$workspaceFolder/lib" imported by default
],
```

For whatever reason every module we use is identified on mouseover and navigable given everything in our `carton exec -- perl -V`'s `@INC` and what is added manually above. Unfortunately no subroutines have mouse over identification or navigability and we cannot seem to get object recognition or autocomplete working. We use Moose heavily. Our repo is quite large. Please let me know if I can provide additional information.

**Comment by bscan** [comment]
Hi @stevenwittkopf,
I use the Perl Navigator primarily on a remote linux server with a large repo with the vscode ssh extension so it should work well. Does it work with simple files? If you just open a file with a few imports and define a simple subroutines?

There are three distinct sources of information the Navigator uses, perhaps something is wrong with one of them

1. Module listing: this sounds like it's working and comes from modHunter.pl. Navigation to Modules is often done from here. If you type a `use` statement, the autocompletion will be done based on this set of available modules. 

2. Compilation: the Navigator runs `perl -c` on your open file and then inspects the symbol table to see what is populated. This generally finds all loaded packages and imported subroutines. There is currently an issue where "namespace::clean" and autoclean interferes with this capability by cleaning the symbol table before I can read it. Otherwise, it works very well with Moose, including go-to definition on attributes of imported modules. You can also tell this works by ensuring you do not have any syntax errors in your file (and if you add one, the Navigator marks the file as "red"). If you have `use File::Path qw(make_path);` in your file, you should be able to go-to definition to `make_path` for example.

3. Tagging: The symbols in the current file itself are found by the tagger which picks up variables, etc. Go-to definition within a file works from this. This you can test by doing a go-to definition on a sub within the same file. 
 
If something doesn't work after restarting vscode (which restarts the language server), take a look at the logs (log location shown in an attached image). See if any errors jump out. The most important line is "Starting perl compilation check with the equivalent of" 

`perl -c -MInquisitor /path/to/file.pl`

You can run this command on its own and check the output, which is a combination of points 2 and 3 above and will list all the relevant subs and variables. See if it errors or anything.

![image](https://user-images.githubusercontent.com/10503608/207437410-e4bd7830-2277-444f-ba1d-a18d66b3bd32.png)

**Comment by stevenwittkopf** [comment]
Hi. Thanks for your reply.

1) Though modules can be navigated to via ctrl+click and there is a tooltip name given on mouseover, typing 'use' does not bring up a list of modules to populate with.
2-3) When I try to include the inquisitor module it says it is not found. I can't find a module by that name on cpan or metacpan.

Additionally when I run the perl -c command with the necessary includes I get a message on any given model that says "<filename> Syntax OK"

Could it be due to the Inquisitor module being absent?

**Comment by stevenwittkopf** [comment]
```
[Trace - 5:42:20 PM] Sending request 'initialize - (0)'.
[Trace - 5:42:21 PM] Received response 'initialize - (0)' in 611ms.
[Trace - 5:42:21 PM] Sending notification 'initialized'.
[Trace - 5:42:21 PM] Sending notification 'workspace/didChangeConfiguration'.
[Trace - 5:42:21 PM] Sending notification 'textDocument/didOpen'.
[Trace - 5:42:21 PM] Received request 'client/registerCapability - (0)'.
[Trace - 5:42:21 PM] Sending response 'client/registerCapability - (0)'. Processing request took 0ms
[Trace - 5:42:21 PM] Received request 'client/registerCapability - (1)'.
[Trace - 5:42:21 PM] Sending response 'client/registerCapability - (1)'. Processing request took 1ms
[Trace - 5:42:21 PM] Received request 'workspace/configuration - (2)'.
[Trace - 5:42:21 PM] Sending response 'workspace/configuration - (2)'. Processing request took 1ms
[Trace - 5:42:21 PM] Received request 'workspace/configuration - (3)'.
[Trace - 5:42:21 PM] Sending response 'workspace/configuration - (3)'. Processing request took 0ms
Found settings
[Trace - 5:42:21 PM] Received request 'workspace/workspaceFolders - (4)'.
[Trace - 5:42:21 PM] Sending response 'workspace/workspaceFolders - (4)'. Processing request took 0ms
[Trace - 5:42:21 PM] Received request 'workspace/workspaceFolders - (5)'.
[Trace - 5:42:21 PM] Sending response 'workspace/workspaceFolders - (5)'. Processing request took 0ms
Starting perl compilation check with the equivalent of: /home/swittkop/.plenv-centos7/versions/gsg-epay/bin/perl -c -Mwarnings -M-warnings=redefine -I /home/swittkop/gsg-epay/t/lib/ -I /home/swittkop/gsg-epay/lib -I /home/swittkop/.vscode-server/extensions/bscan.perlnavigator-0.4.1/server/src/perl -MInquisitor /home/swittkop/gsg-epay/lib/GSG/Epay/Biz/CDL/Logger.pm
Starting to look for perl modules with -I /home/swittkop/gsg-epay/t/lib/ -I /home/swittkop/gsg-epay/lib /home/swittkop/.vscode-server/extensions/bscan.perlnavigator-0.4.1/server/src/perl/lib_bs22/ModHunter.pl
[Trace - 5:42:21 PM] Sending notification '$/setTrace'.
[Trace - 5:42:21 PM] Sending notification 'workspace/didChangeConfiguration'.
[Trace - 5:42:21 PM] Received request 'workspace/configuration - (6)'.
[Trace - 5:42:21 PM] Sending response 'workspace/configuration - (6)'. Processing request took 1ms
[Trace - 5:42:21 PM] Received request 'workspace/workspaceFolders - (7)'.
[Trace - 5:42:21 PM] Sending response 'workspace/workspaceFolders - (7)'. Processing request took 0ms
Starting to look for perl modules with -I /home/swittkop/gsg-epay/t/lib/ -I /home/swittkop/gsg-epay/lib /home/swittkop/.vscode-server/extensions/bscan.perlnavigator-0.4.1/server/src/perl/lib_bs22/ModHunter.pl
[Trace - 5:42:21 PM] Sending notification '$/setTrace'.
[Trace - 5:42:21 PM] Sending notification 'workspace/didChangeConfiguration'.
[Trace - 5:42:21 PM] Received request 'workspace/configuration - (8)'.
[Trace - 5:42:21 PM] Sending response 'workspace/configuration - (8)'. Processing request took 1ms
[Trace - 5:42:21 PM] Sending notification '$/setTrace'.
[Trace - 5:42:21 PM] Sending notification 'workspace/didChangeConfiguration'.
[Trace - 5:42:21 PM] Sending notification '$/setTrace'.
[Trace - 5:42:21 PM] Sending notification 'workspace/didChangeConfiguration'.
[Trace - 5:42:21 PM] Received request 'workspace/workspaceFolders - (9)'.
[Trace - 5:42:21 PM] Sending response 'workspace/workspaceFolders - (9)'. Processing request took 0ms
[Trace - 5:42:21 PM] Received request 'workspace/configuration - (10)'.
[Trace - 5:42:21 PM] Sending response 'workspace/configuration - (10)'. Processing request took 0ms
Starting to look for perl modules with -I /home/swittkop/gsg-epay/t/lib/ -I /home/swittkop/gsg-epay/lib /home/swittkop/.vscode-server/extensions/bscan.perlnavigator-0.4.1/server/src/perl/lib_bs22/ModHunter.pl
[Trace - 5:42:21 PM] Received request 'workspace/configuration - (11)'.
[Trace - 5:42:21 PM] Sending response 'workspace/configuration - (11)'. Processing request took 1ms
[Trace - 5:42:21 PM] Sending request 'textDocument/documentSymbol - (1)'.
[Trace - 5:42:21 PM] Received request 'workspace/workspaceFolders - (12)'.
[Trace - 5:42:21 PM] Sending response 'workspace/workspaceFolders - (12)'. Processing request took 0ms
[Trace - 5:42:21 PM] Received request 'workspace/workspaceFolders - (13)'.
[Trace - 5:42:21 PM] Sending response 'workspace/workspaceFolders - (13)'. Processing request took 0ms
Starting to look for perl modules with -I /home/swittkop/gsg-epay/t/lib/ -I /home/swittkop/gsg-epay/lib /home/swittkop/.vscode-server/extensions/bscan.perlnavigator-0.4.1/server/src/perl/lib_bs22/ModHunter.pl
Starting to look for perl modules with -I /home/swittkop/gsg-epay/t/lib/ -I /home/swittkop/gsg-epay/lib /home/swittkop/.vscode-server/extensions/bscan.perlnavigator-0.4.1/server/src/perl/lib_bs22/ModHunter.pl
[Trace - 5:42:21 PM] Sending notification '$/cancelRequest'.
[Trace - 5:42:21 PM] Sending request 'textDocument/documentSymbol - (2)'.
Found settings
[Trace - 5:42:22 PM] Received request 'workspace/workspaceFolders - (14)'.
[Trace - 5:42:22 PM] Sending response 'workspace/workspaceFolders - (14)'. Processing request took 0ms
Starting perl compilation check with the equivalent of: /home/swittkop/.plenv-centos7/versions/gsg-epay/bin/perl -c -Mwarnings -M-warnings=redefine -I /home/swittkop/gsg-epay/t/lib/ -I /home/swittkop/gsg-epay/lib -I /home/swittkop/.vscode-server/extensions/bscan.perlnavigator-0.4.1/server/src/perl -MInquisitor /home/swittkop/gsg-epay/lib/GSG/Epay/Biz/CDL/Logger.pm
Compilation Time: 1.874 seconds
[Trace - 5:42:23 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 5:42:23 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 5:42:23 PM] Received response 'textDocument/documentSymbol - (2)' in 1259ms.
[Trace - 5:42:23 PM] Received response 'textDocument/documentSymbol - (1)' in 1346ms.
Compilation Time: 1.514 seconds
[Trace - 5:42:23 PM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 5:42:23 PM] Received notification 'textDocument/publishDiagnostics'.
Success running mod hunter
Success running mod hunter
Success running mod hunter
Success running mod hunter
Success running mod hunter

```

This is what I see under output upon reloading the window (or restarting vs code)

**Comment by stevenwittkopf** [comment]
https://pastebin.com/Fw5pEvWq with trace server set to "verbose>

**Comment by stevenwittkopf** [comment]
Inquisitor appears to work if I provide the necessary Include /home/swittkop/.vscode-server/extensions/bscan.perlnavigator-0.4.1/server/src/perl/ It spits out quite a lot.

**Comment by bscan** [comment]
Yes, `/home/swittkop/.plenv-centos7/versions/gsg-epay/bin/perl -c -Mwarnings -M-warnings=redefine -I /home/swittkop/gsg-epay/t/lib/ -I /home/swittkop/gsg-epay/lib -I /home/swittkop/.vscode-server/extensions/bscan.perlnavigator-0.4.1/server/src/perl -MInquisitor /home/swittkop/gsg-epay/lib/GSG/Epay/Biz/CDL/Logger.pm`
is the key line. Running it shows the full list of symbols that the Navigator is able to use for navigation and autocomplete (with the exception of the set of modules). The fact that those symbols are recognized and it's not working is odd. FWIW, I also use centos7 with vscode, so this should be a pretty well tested layout. You could try piping that Inquisitor output to a file and scanning to see if the symbols you need are defined, but it is almost certainly is working. Perhaps try it on a simple file with a subroutine or two and the set of symbols would be fairly small. 

Perhaps something is odd with your filesystem? Are any of the dependencies located in symlinked directory instead of a normal one? (Although I wouldn't normally expect that to be an issue either). 

Another approach could be enabling verbose logging in the settings. In your json settings, if you add `    "perlnavigator.trace.server": "verbose", ` You'll get more detailed logs. For example, this is what I see for a hover request and a goto definition. You can see the request from the client and the response from the server.

```
    [Trace - 6:18:03 PM] Sending request 'textDocument/hover - (26401)'.
Params: {
    "textDocument": {
        "uri": "file:///home/brian/sandbox/sandbox.pl"
    },
    "position": {
        "line": 8,
        "character": 6
    }
}


[Trace - 6:18:03 PM] Received response 'textDocument/hover - (26401)' in 1ms.
Result: {
    "contents": "(module) Frob3: /tmp/navTests/.plenv-centos7/Frob3.pm"
}


[Trace - 6:18:07 PM] Sending request 'textDocument/definition - (26402)'.
Params: {
    "textDocument": {
        "uri": "file:///home/brian/sandbox/sandbox.pl"
    },
    "position": {
        "line": 8,
        "character": 7
    }
}


[Trace - 6:18:07 PM] Received response 'textDocument/definition - (26402)' in 4ms.
Result: [
    {
        "uri": "file:///tmp/navTests/.plenv-centos7/Frob3.pm",
        "range": {
            "start": {
                "line": 0,
                "character": 0
            },
            "end": {
                "line": 0,
                "character": 500
            }
        }
    }
]
```

**Comment by stevenwittkopf** [comment]
With verbose on, mouseover just says there are no results. I tried to create a simple file with no imports and it works beautifully.

There is an error (discovered after I initially posted) when running my command that reads as follows: `PN:inquistor failed with error: Can't use string ("REDACTED::Utils::Prototype") as a HASH ref while "strict refs" in use at /usr/local/REDACTED line 1616.`. So it seems we have some issue with a system module.

**Comment by stevenwittkopf** [comment]
Just as an update, some ancient perl wizards at my company are now taking a look at this error.
![image](https://user-images.githubusercontent.com/58092619/207473768-e2881ac2-e200-4eda-b0a3-c20cdc6fb6f9.png)

**Comment by bscan** [comment]
Nice, thanks! Tom Christiansen wrote the perl book sitting on my desk 😆 . That's a great find and subtle.  Seems like there are two issues here; I'm using the wrong `->can` method, and I'm also not using nearly enough `eval`s. Currently it seems to break the whole thing when an error occurs in the Inquisitor. Although errors in that part of the the code have been very rare.

Using the `sub can` code snippet, I was able to reproduce the issue locally. I just committed this: https://github.com/bscan/PerlNavigator/commit/14a6eb781077357e26b581cf56172aa82ec446f5 which fixes it for me locally. I pushed these fixes to the marketplace if you can try them out (version 0.4.6). You'll likely need to reload vscode as well. 

I'd also like to go back and add some more eval statements, to get a more graceful degradation in the event of errors.  Let me know if the initial fixes work though. Thanks!

**Comment by stevenwittkopf** [comment]
I am so grateful for your quick fix and so happy we could get to the bottom of the issue. It is working great and it is really a thing of beauty to behold. I'm sure when my coworkers log in tomorrow they'll be pleasantly surprised with all of perl navigator's "new" features after the update! Thanks again.

**Comment by bscan** [comment]
Awesome, I'm glad it's working. Thank you for debugging, and please extend my gratitude to Tom as well for his help on this one. 

If you find any other limitations or quirks, please let me know (this thread is fine, or feel free to open more tickets, or start a "discussion" post). The Navigator should work well with Moose including syntax highlighting, knowledge of attributes vs methods, etc, but I'm always open to improvements. The syntax highlighting (e.g. highlighting `has`  and `extends`) is the newest feature so may have opportunities for improvement.
