### ISSUE TITLE
How to add unit tests for criticWrapperl.pl ?

### ISSUE THREAD

**Issue by hakonhagland** [bscan/PerlNavigator#65]
I am testing a regex `criticWrapper.pl` to fix #63, similar to what is done in `adjustForKeywords()`: 

https://github.com/bscan/PerlNavigator/blob/31b6d7b4b110821ea7550abb0dde53ebe94e5cd3/server/src/perl/criticWrapper.pl#L34

I would like to test this regex with different input files (the ones that are given to `criticWrapper.pl` on STDIN). My first thought was to use unit tests with e.g. `Test::More`. Where to put these tests? And how/when are they run? I can see one unit test is already present here:

https://github.com/bscan/PerlNavigator/blob/main/t/01_MyClass.t

**Comment by bscan** [comment]
Hi @hakonhagland . Currently, there are not any automated tests for the Navigator. They're tricky to write due to the layout of the Navigator (cross-language, perl side runs during compile phase, etc). However, it's certainly a good idea to be thinking in that direction. I'd happily accept pull requests that add tests, even if they need to be run manually for now. Then adding Github actions that automatically run them would be cool too.

**Comment by bscan** [comment]
Closing for now, although unit tests are still high on my list.
