### ISSUE TITLE
Errors contain aboslute path to affected file

### ISSUE THREAD

**Issue by CodingMarkus** [bscan/PerlNavigator#75]
Errors always contain the full absolute path, e.g.

```
Syntax: Can't redeclare "my" in "my" at /Users/<user>/Documents/blah/blup/project-name/file_name.pl line 24, near "my"
```

No other language server I use prints errors like this which is pretty annoying if you edit a simple Perl file. All others don't name the file at all, as the error is only displayed for the currently active file and thus also refer to that file and if the error refers to other files in a project, they show a project relative path.

**Comment by bscan** [comment]
Hi @CodingMarkus, thanks for the report. Which editor and Navigator version are you using? This should've been fixed in January for the currently active file https://github.com/bscan/PerlNavigator/commit/e0e119f557b3639fb7ce6b4d030f020ccd2179e3 

See example below, where a syntax error in the currently active file does not display the path. 

The Navigator has code to "localize" errors as well. If a loaded module throws an error or a warning, it will try to display that diagnostic on the line where the module is imported (e.g. Foo's warnings are shown on the `use Foo` line). However, I like the idea of displaying a project relative path when possible. If a file path starts with a workspace path, it would be nice to strip that part out. This won't always work, as there will still be cases where other dependencies outside of the project will throw errors.  

![image](https://github.com/bscan/PerlNavigator/assets/10503608/9dd41cbb-fc0b-411f-9633-0412379aa5ad)

**Comment by CodingMarkus** [comment]
Ah, my bad. I got it from here

https://open-vsx.org/extension/bscan/perlnavigator

so I assumed that is the latest version available, after all it seemed you have published it there yourself. I'll try the latest release instead.

**Comment by CodingMarkus** [comment]
You are correct, is fixed.

![Screenshot 2023-06-14 at 15 49 20](https://github.com/bscan/PerlNavigator/assets/26418089/318f07da-e878-4e16-bc9a-ef4089fe58a2)

My apologies again, I should have first checked if that is really the latest version.

**Comment by bscan** [comment]
Thanks, I just published the latest version to the Open-VSX store. Currently, there is a Github action that publishes automatically to the npm registry, but I need to manually publish to the vscode Marketplace and the Open-VSX Marketplace. Thank you for the report.
