### ISSUE TITLE
Adding support for Dancer methods

### ISSUE THREAD

**Issue by ulizama** [bscan/PerlNavigator#84]
There is a feature that I would love for the extension to have and that is to be able to support Dancer routes and identify them as symbols like it's done with methods.

For example:

```
get '/vehicles' => sub {

};

```

Would then become symbol **get 'vehicles'** so it can be searched via symbol search on the file.

I'm willing to give it a try if I could get pointed in the right direction as I've never played around with VS extensions.

**Comment by bscan** [comment]
![image](https://github.com/bscan/PerlNavigator/assets/10503608/bfdfbcd6-5396-4e27-97bd-a30b677fcaf5)

Thank you for the suggestion. I just committed an initial version, and it should be available in the marketplace now in version 0.6.1. 

Adding support for new frameworks is a bit tricky because of the number of different places impacted. I added to the tagger, and then modified the locations for symbol types, hover, and completion. I also added custom syntax highlighting and generally tried to match the syntax highlighting regexes to the ones used for parsing the symbols. 

Thank you for the offer to help as well. I don't use Dancer/Dancer2 in my work, so a review and testing would be extremely helpful. As you use this, I'm sure you'll come across parsing bugs, missing keywords, etc. I hope the layout makes sense if you wanted to make any changes or add any other features to the Navigator.

In terms of getting started with a testing environment, I just added additional details to the Contributing page https://github.com/bscan/PerlNavigator/blob/main/CONTRIBUTING.md 
Let me know if you have any issues and I'm more than happy to help out.

**Comment by ulizama** [comment]
Great! I looked at the commit and I see the changes you implemented, I think they are clear enough for me to follow-up on them to make some contributions if needed, at least on the Dancer side of things.

I'll try to do some testing over the weekend.

**Comment by ulizama** [comment]
@bscan Just requested my first PR. Let me know your thoughts or if you would like me to do anything else to get it approved.

Thanks!

**Comment by bscan** [comment]
Just published your updates in version 0.6.2 to the vscode marketplace and to NPM. Thanks again for the feature.
